### ISSUE TITLE
Unable to resolve type

### ISSUE THREAD

**Issue by Arrowerse2001** [dinesh-solanki/Folicon#1]
Hi, Thanks for creating this. However I cloned it added my TMDB API into App.config everything should be fine in there but since there was no way to run it I opened visual studio and tried to compile it however i get this error everytime i compile the code.

Unable to resolve type 'DevExpress.Xpf.NavBar.NavBarControl, DevExpress.Xpf.NavBar.v19.1, Version=19.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'	

EDIT: I changed the public key to T296988 and it removed the above error and only gives one error now which is The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)'

**Comment by dinesh-solanki** [comment]
Fixed,
I accidentally had Dropped a DevX control, which caused the Licence file to generate, i deleted control and the references but forgot the licence file. Please try again.

**Comment by dinesh-solanki** [comment]
Fixed,
I accidentally Dropped a DevX control, which caused the Licence file to generate, I deleted control and the references but forgot the licence file. Please try again.

> 
> 
> Hi, Thanks for creating this. However I cloned it added my TMDB API into App.config everything should be fine in there but since there was no way to run it I opened visual studio and tried to compile it however i get this error everytime i compile the code.
> 
> Unable to resolve type 'DevExpress.Xpf.NavBar.NavBarControl, DevExpress.Xpf.NavBar.v19.1, Version=19.1.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'
> 
> EDIT: I changed the public key to T296988 and it removed the above error and only gives one error now which is The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)'

**Comment by dinesh-solanki** [comment]
@Arrowerse2001 is the issue solved?

**Comment by Arrowerse2001** [comment]
Yes. Sorry lol
